project:
  type: book
  output-dir: docs

book:
  title: "Cohort analysis"
  author: "Ian Gow"
  date: today
  date-format: "D MMMM YYYY"

  chapters:
    - index.qmd
    - original_sql.qmd
    - ctes_comments.qmd
    - dbplyr.qmd
    - intermezzo.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
