project:
  type: book
  output-dir: docs

book:
  title: "Cohort analysis"
  author: "Ian Gow"
  date: today
  date-format: "D MMMM YYYY"

  chapters:
    - index.qmd
    - original_sql.qmd
    - ctes_comments.qmd
    - dbplyr.qmd
    - intermezzo.qmd
    - revised.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    include-in-header:
      text: |
        \usepackage[group-digits = integer, group-separator={,}, group-minimum-digits = 4]{siunitx}
        \usepackage{imakeidx}
        \usepackage{booktabs}
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    number-sections: true
    colorlinks: true
    keep-tex: false
